name: caws-endpoint
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.10.12
  - xtb-python=22.1
  - pip:
      - ase==3.22.1
      - numpy==1.25.2
      - pillow==10.0.0
      - psycopg2-binary==2.9.7
      - python-igraph==0.10.8
      - rdkit==2023.9.3
      - scikit-learn==1.3.1
      - scipy==1.11.
      - squiggle==0.3.1
      - globus-compute-endpoint @ git+https://github.com/AK2000/funcX@power_monitoring_new#subdirectory=compute_endpoint,
      - -e chemfunctions @ git+https://github.com/AK2000/molecular-design-parsl-demo.git